modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.heat_lamp]]
    modId="forge"
    mandatory=true
    versionRange="[47.3.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heat_lamp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Heat Lamp adds warming mechanics and light sources to Minecraft.
'''
